// Donation Creation
export const CREATE_DONATION_REQUEST = 'CREATE_DONATION_REQUEST';
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS';
export const CREATE_DONATION_FAIL = 'CREATE_DONATION_FAIL';

export const CREATE_RECURRING_DONATION_REQUEST = 'CREATE_RECURRING_DONATION_REQUEST';
export const CREATE_RECURRING_DONATION_SUCCESS = 'CREATE_RECURRING_DONATION_SUCCESS';
export const CREATE_RECURRING_DONATION_FAIL = 'CREATE_RECURRING_DONATION_FAIL';

// Donation Listing
export const GET_DONATIONS_REQUEST = 'GET_DONATIONS_REQUEST';
export const GET_DONATIONS_SUCCESS = 'GET_DONATIONS_SUCCESS';
export const GET_DONATIONS_FAIL = 'GET_DONATIONS_FAIL';

export const GET_ALL_DONATIONS_REQUEST = 'GET_ALL_DONATIONS_REQUEST';
export const GET_ALL_DONATIONS_SUCCESS = 'GET_ALL_DONATIONS_SUCCESS';
export const GET_ALL_DONATIONS_FAIL = 'GET_ALL_DONATIONS_FAIL';

// Single Donation
export const GET_DONATION_BY_ID_REQUEST = 'GET_DONATION_BY_ID_REQUEST';
export const GET_DONATION_BY_ID_SUCCESS = 'GET_DONATION_BY_ID_SUCCESS';
export const GET_DONATION_BY_ID_FAIL = 'GET_DONATION_BY_ID_FAIL';

export const GET_DONATIONS_BY_CAMPAIGN_REQUEST = 'GET_DONATIONS_BY_CAMPAIGN_REQUEST';
export const GET_DONATIONS_BY_CAMPAIGN_SUCCESS = 'GET_DONATIONS_BY_CAMPAIGN_SUCCESS';
export const GET_DONATIONS_BY_CAMPAIGN_FAIL = 'GET_DONATIONS_BY_CAMPAIGN_FAIL';

// Donation Updates
export const UPDATE_DONATION_STATUS_REQUEST = 'UPDATE_DONATION_STATUS_REQUEST';
export const UPDATE_DONATION_STATUS_SUCCESS = 'UPDATE_DONATION_STATUS_SUCCESS';
export const UPDATE_DONATION_STATUS_FAIL = 'UPDATE_DONATION_STATUS_FAIL';

// Stats
export const GET_DONATION_STATS_REQUEST = 'GET_DONATION_STATS_REQUEST';
export const GET_DONATION_STATS_SUCCESS = 'GET_DONATION_STATS_SUCCESS';
export const GET_DONATION_STATS_FAIL = 'GET_DONATION_STATS_FAIL';

// Webhook
export const DONATION_WEBHOOK_SUCCESS = 'DONATION_WEBHOOK_SUCCESS';