export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';

export const GET_EVENT_BY_ID_REQUEST = 'GET_EVENT_BY_ID_REQUEST';
export const GET_EVENT_BY_ID_SUCCESS = 'GET_EVENT_BY_ID_SUCCESS';
export const GET_EVENT_BY_ID_FAIL = 'GET_EVENT_BY_ID_FAIL';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

export const CANCEL_EVENT_REQUEST = 'CANCEL_EVENT_REQUEST';
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS';
export const CANCEL_EVENT_FAIL = 'CANCEL_EVENT_FAIL';

export const REGISTER_FOR_EVENT_REQUEST = 'REGISTER_FOR_EVENT_REQUEST';
export const REGISTER_FOR_EVENT_SUCCESS = 'REGISTER_FOR_EVENT_SUCCESS';
export const REGISTER_FOR_EVENT_FAIL = 'REGISTER_FOR_EVENT_FAIL';

export const GET_EVENTS_BY_ORGANIZER_REQUEST = 'GET_EVENTS_BY_ORGANIZER_REQUEST';
export const GET_EVENTS_BY_ORGANIZER_SUCCESS = 'GET_EVENTS_BY_ORGANIZER_SUCCESS';
export const GET_EVENTS_BY_ORGANIZER_FAIL = 'GET_EVENTS_BY_ORGANIZER_FAIL';

export const SEARCH_EVENTS_REQUEST = 'SEARCH_EVENTS_REQUEST';
export const SEARCH_EVENTS_SUCCESS = 'SEARCH_EVENTS_SUCCESS';
export const SEARCH_EVENTS_FAIL = 'SEARCH_EVENTS_FAIL';

export const GET_MY_EVENTS_REQUEST = 'GET_MY_EVENTS_REQUEST';
export const GET_MY_EVENTS_SUCCESS = 'GET_MY_EVENTS_SUCCESS';
export const GET_MY_EVENTS_FAIL = 'GET_MY_EVENTS_FAIL';