// Job Creation
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

// Job Listing
export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL';

export const GET_ALL_JOBS_REQUEST = 'GET_ALL_JOBS_REQUEST';
export const GET_ALL_JOBS_SUCCESS = 'GET_ALL_JOBS_SUCCESS';
export const GET_ALL_JOBS_FAIL = 'GET_ALL_JOBS_FAIL';

// Single Job
export const GET_JOB_BY_ID_REQUEST = 'GET_JOB_BY_ID_REQUEST';
export const GET_JOB_BY_ID_SUCCESS = 'GET_JOB_BY_ID_SUCCESS';
export const GET_JOB_BY_ID_FAIL = 'GET_JOB_BY_ID_FAIL';

// Job Updates
export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL';

export const CLOSE_JOB_REQUEST = 'CLOSE_JOB_REQUEST';
export const CLOSE_JOB_SUCCESS = 'CLOSE_JOB_SUCCESS';
export const CLOSE_JOB_FAIL = 'CLOSE_JOB_FAIL';

export const FORCE_CLOSE_JOB_REQUEST = 'FORCE_CLOSE_JOB_REQUEST';
export const FORCE_CLOSE_JOB_SUCCESS = 'FORCE_CLOSE_JOB_SUCCESS';
export const FORCE_CLOSE_JOB_FAIL = 'FORCE_CLOSE_JOB_FAIL';

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL';

// Applications
export const APPLY_FOR_JOB_REQUEST = 'APPLY_FOR_JOB_REQUEST';
export const APPLY_FOR_JOB_SUCCESS = 'APPLY_FOR_JOB_SUCCESS';
export const APPLY_FOR_JOB_FAIL = 'APPLY_FOR_JOB_FAIL';

export const GET_JOB_APPLICATIONS_REQUEST = 'GET_JOB_APPLICATIONS_REQUEST';
export const GET_JOB_APPLICATIONS_SUCCESS = 'GET_JOB_APPLICATIONS_SUCCESS';
export const GET_JOB_APPLICATIONS_FAIL = 'GET_JOB_APPLICATIONS_FAIL';

export const GET_ALL_APPLICATIONS_REQUEST = 'GET_ALL_APPLICATIONS_REQUEST';
export const GET_ALL_APPLICATIONS_SUCCESS = 'GET_ALL_APPLICATIONS_SUCCESS';
export const GET_ALL_APPLICATIONS_FAIL = 'GET_ALL_APPLICATIONS_FAIL';

// User-specific
export const GET_MY_POSTED_JOBS_REQUEST = 'GET_MY_POSTED_JOBS_REQUEST';
export const GET_MY_POSTED_JOBS_SUCCESS = 'GET_MY_POSTED_JOBS_SUCCESS';
export const GET_MY_POSTED_JOBS_FAIL = 'GET_MY_POSTED_JOBS_FAIL';

export const GET_MY_APPLIED_JOBS_REQUEST = 'GET_MY_APPLIED_JOBS_REQUEST';
export const GET_MY_APPLIED_JOBS_SUCCESS = 'GET_MY_APPLIED_JOBS_SUCCESS';
export const GET_MY_APPLIED_JOBS_FAIL = 'GET_MY_APPLIED_JOBS_FAIL';

// Search
export const SEARCH_JOBS_REQUEST = 'SEARCH_JOBS_REQUEST';
export const SEARCH_JOBS_SUCCESS = 'SEARCH_JOBS_SUCCESS';
export const SEARCH_JOBS_FAIL = 'SEARCH_JOBS_FAIL';