// Mentorship Request
export const REQUEST_MENTORSHIP_REQUEST = 'REQUEST_MENTORSHIP_REQUEST';
export const REQUEST_MENTORSHIP_SUCCESS = 'REQUEST_MENTORSHIP_SUCCESS';
export const REQUEST_MENTORSHIP_FAIL = 'REQUEST_MENTORSHIP_FAIL';

// Get Mentors
export const GET_MENTORS_REQUEST = 'GET_MENTORS_REQUEST';
export const GET_MENTORS_SUCCESS = 'GET_MENTORS_SUCCESS';
export const GET_MENTORS_FAIL = 'GET_MENTORS_FAIL';

// Get Mentorship Requests
export const GET_MENTORSHIP_REQUESTS_REQUEST = 'GET_MENTORSHIP_REQUESTS_REQUEST';
export const GET_MENTORSHIP_REQUESTS_SUCCESS = 'GET_MENTORSHIP_REQUESTS_SUCCESS';
export const GET_MENTORSHIP_REQUESTS_FAIL = 'GET_MENTORSHIP_REQUESTS_FAIL';

// Accept/Reject Mentorship
export const ACCEPT_MENTORSHIP_REQUEST = 'ACCEPT_MENTORSHIP_REQUEST';
export const ACCEPT_MENTORSHIP_SUCCESS = 'ACCEPT_MENTORSHIP_SUCCESS';
export const ACCEPT_MENTORSHIP_FAIL = 'ACCEPT_MENTORSHIP_FAIL';

export const REJECT_MENTORSHIP_REQUEST = 'REJECT_MENTORSHIP_REQUEST';
export const REJECT_MENTORSHIP_SUCCESS = 'REJECT_MENTORSHIP_SUCCESS';
export const REJECT_MENTORSHIP_FAIL = 'REJECT_MENTORSHIP_FAIL';

export const RESPOND_TO_REQUEST_REQUEST = 'RESPOND_TO_REQUEST_REQUEST';
export const RESPOND_TO_REQUEST_SUCCESS = 'RESPOND_TO_REQUEST_SUCCESS';
export const RESPOND_TO_REQUEST_FAIL = 'RESPOND_TO_REQUEST_FAIL';

// Active Mentorships
export const GET_ACTIVE_MENTORSHIPS_REQUEST = 'GET_ACTIVE_MENTORSHIPS_REQUEST';
export const GET_ACTIVE_MENTORSHIPS_SUCCESS = 'GET_ACTIVE_MENTORSHIPS_SUCCESS';
export const GET_ACTIVE_MENTORSHIPS_FAIL = 'GET_ACTIVE_MENTORSHIPS_FAIL';

// Mentorship Completion
export const COMPLETE_MENTORSHIP_REQUEST = 'COMPLETE_MENTORSHIP_REQUEST';
export const COMPLETE_MENTORSHIP_SUCCESS = 'COMPLETE_MENTORSHIP_SUCCESS';
export const COMPLETE_MENTORSHIP_FAIL = 'COMPLETE_MENTORSHIP_FAIL';

// Meetings
export const ADD_MEETING_REQUEST = 'ADD_MEETING_REQUEST';
export const ADD_MEETING_SUCCESS = 'ADD_MEETING_SUCCESS';
export const ADD_MEETING_FAIL = 'ADD_MEETING_FAIL';

// Mentorship Details
export const GET_MENTORSHIP_DETAILS_REQUEST = 'GET_MENTORSHIP_DETAILS_REQUEST';
export const GET_MENTORSHIP_DETAILS_SUCCESS = 'GET_MENTORSHIP_DETAILS_SUCCESS';
export const GET_MENTORSHIP_DETAILS_FAIL = 'GET_MENTORSHIP_DETAILS_FAIL';

// User Mentorships
export const GET_USER_MENTORSHIPS_REQUEST = 'GET_USER_MENTORSHIPS_REQUEST';
export const GET_USER_MENTORSHIPS_SUCCESS = 'GET_USER_MENTORSHIPS_SUCCESS';
export const GET_USER_MENTORSHIPS_FAIL = 'GET_USER_MENTORSHIPS_FAIL';

// Admin
export const GET_ALL_MENTORSHIPS_REQUEST = 'GET_ALL_MENTORSHIPS_REQUEST';
export const GET_ALL_MENTORSHIPS_SUCCESS = 'GET_ALL_MENTORSHIPS_SUCCESS';
export const GET_ALL_MENTORSHIPS_FAIL = 'GET_ALL_MENTORSHIPS_FAIL';

export const GET_MENTORSHIP_STATS_REQUEST = 'GET_MENTORSHIP_STATS_REQUEST';
export const GET_MENTORSHIP_STATS_SUCCESS = 'GET_MENTORSHIP_STATS_SUCCESS';
export const GET_MENTORSHIP_STATS_FAIL = 'GET_MENTORSHIP_STATS_FAIL';

export const CANCEL_MENTORSHIP_REQUEST = 'CANCEL_MENTORSHIP_REQUEST';
export const CANCEL_MENTORSHIP_SUCCESS = 'CANCEL_MENTORSHIP_SUCCESS';
export const CANCEL_MENTORSHIP_FAIL = 'CANCEL_MENTORSHIP_FAIL';

// Search
export const SEARCH_MENTORS_REQUEST = 'SEARCH_MENTORS_REQUEST';
export const SEARCH_MENTORS_SUCCESS = 'SEARCH_MENTORS_SUCCESS';
export const SEARCH_MENTORS_FAIL = 'SEARCH_MENTORS_FAIL';