export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_FAIL = 'GET_POST_BY_ID_FAIL';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const UPVOTE_POST_REQUEST = 'UPVOTE_POST_REQUEST';
export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS';
export const UPVOTE_POST_FAIL = 'UPVOTE_POST_FAIL';

export const GET_POSTS_BY_TAG_REQUEST = 'GET_POSTS_BY_TAG_REQUEST';
export const GET_POSTS_BY_TAG_SUCCESS = 'GET_POSTS_BY_TAG_SUCCESS';
export const GET_POSTS_BY_TAG_FAIL = 'GET_POSTS_BY_TAG_FAIL';

export const GET_POSTS_BY_AUTHOR_REQUEST = 'GET_POSTS_BY_AUTHOR_REQUEST';
export const GET_POSTS_BY_AUTHOR_SUCCESS = 'GET_POSTS_BY_AUTHOR_SUCCESS';
export const GET_POSTS_BY_AUTHOR_FAIL = 'GET_POSTS_BY_AUTHOR_FAIL';

export const SEARCH_POSTS_REQUEST = 'SEARCH_POSTS_REQUEST';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_FAIL = 'SEARCH_POSTS_FAIL';

export const GET_POST_ANALYTICS_REQUEST = 'GET_POST_ANALYTICS_REQUEST';
export const GET_POST_ANALYTICS_SUCCESS = 'GET_POST_ANALYTICS_SUCCESS';
export const GET_POST_ANALYTICS_FAIL = 'GET_POST_ANALYTICS_FAIL';